Update README links to documentation
rtfd/recommonmark pull request #67
Opened 2017-04-07 09:53 UTC by fievelk

Previous links did not consider the `docs/` folder. These changes fix the problem.

2017-04-09 02:53 UTC, Blendify commented
LGTM but I cannot merge.

2017-04-14 16:52 UTC, agjohnson commented
This breaks the true docs, as `README.md` is linked as `index.md` in the docs.

2017-04-14 16:53 UTC, agjohnson requested changes
This needs to respect how `docs/index.md` is using `README.md`

2018-03-02 14:29 UTC, Pawamoy commented
Maybe don't use a symlink then? And write an actual `index.md` for the docs? From a personal point of view, the README should not always be used as the introductory file of the documentation, though I agree it's convenient.

2018-03-02 14:32 UTC, Pawamoy commented
Besides, the links don't even work in the documentation.
![screenshot - 03022018 - 03 31 25 pm](https://user-images.githubusercontent.com/3999221/36903737-dd7bd1d0-1e2e-11e8-984d-6703996e5aaa.png)

2018-10-16 09:44 UTC, ericholscher commented
Not sure the best way to solve this. We don't want to include the same content twice, but having broken links in our GH README is not the best outcome :/

2022-03-24 20:30 UTC, closed without merging